"use client";

import { SessionProvider } from "next-auth/react";
import "./globals.css";
import AppBar from "@/components/AppBar";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <AppBar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
